### ISSUE TITLE
Broken? or am I missing something?

### ISSUE THREAD

**Issue by LeeThompson** [joakibj/tswrdb#2]
I got it compiled and tests ok and I can list all the resource types in the RDBs, however, when I try to do any export, the resource ID is shown as an unknown argument:

> run export 1010042 --tsw """D:\Projects\TSW\Input"""
> [info] Running com.joakibj.tswrdb.TswRdb export 1010042 --tsw D:\Projects\TSW\I
> put
> [info] Error: Unknown argument '1010042'
> 
> run export 1020005 --tsw """D:\Projects\TSW\Input"""
> [info] Running com.joakibj.tswrdb.TswRdb export 1020005 --tsw D:\Projects\TSW\In
> put
> [info] Error: Unknown argument '1020005'

(project is set to tswrdb-cmdui)
git pull: 09/17/2013
scala and sbt are fresh (downloaded 9/17/2013 as well)

**Comment by joakibj** [comment]
Ah, sorry. There is an error in the README. It has not been updated to the correct export syntax in the usage examples.

Correct should be:
    run export **rdbtype** 1010042 --tsw """D:\Projects\TSW\Input"""

**Comment by joakibj** [comment]
Please let me know if you have any more issues and thanks for trying it out!

New patch tomorrow so will probably be some goodies there ;)
