### ISSUE TITLE
[ export rdbtype 1010008] java.lang.RuntimeException: Unknown unrecoverable exception occured

### ISSUE THREAD

**Issue by Voyv** [joakibj/tswrdb#3]
Hi,

I wanted to grab some data from secret world mostly skills and items icons but i have this error on rdbtype 1010008.

The others rdbtype are working fine, i did not test all but a few.

Full log :

run export rdbtype 1010008 --tsw """C:\The Secret World"""
[info] Running com.joakibj.tswrdb.TswRdb export rdbtype 1010008 --tsw C:\The Sec
ret World
[info] TSW directory set to: C:\The Secret World
[info] Exporting RdbType: 1010008 (Icons - PNG) into exported/1010008 (Icons - P
NG) ...
[info] Exporting entries from: 0.rdbdata
[error] java.lang.RuntimeException: Unknown unrecoverable exception occured: jav
a.io.FileNotFoundException: Invalid file path
[error]         at com.joakibj.tswrdb.rdb.export.RdbDataExporter$$anonfun$export
$1.apply$mcVI$sp(RdbDataExporter.scala:56)
[info] Unknown unrecoverable exception occured: java.io.FileNotFoundException: I
nvalid file path
[error]         at com.joakibj.tswrdb.rdb.export.RdbDataExporter$$anonfun$export
$1.apply(RdbDataExporter.scala:43)
[info] Exiting...
[error]         at com.joakibj.tswrdb.rdb.export.RdbDataExporter$$anonfun$export
$1.apply(RdbDataExporter.scala:43)
[error]         at scala.collection.Iterator$class.foreach(Iterator.scala:727)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1157
)
[error]         at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:
174)
[error]         at com.joakibj.tswrdb.rdb.export.RdbDataExporter.export(RdbDataE
xporter.scala:42)
[error]         at com.joakibj.tswrdb.rdb.export.RdbDataExporter.exportAll(RdbDa
taExporter.scala:28)
[error]         at com.joakibj.tswrdb.commands.ExportCommands$RdbTypeExportComma
nd.execute(ExportCommands.scala:30)
[error]         at com.joakibj.tswrdb.CommandDispatcher.execute(CommandDispatche
r.scala:45)
[error]         at com.joakibj.tswrdb.CommandDispatcher.dispatch(CommandDispatch
er.scala:31)
[error]         at com.joakibj.tswrdb.TswRdb$$anonfun$15.apply(TswRdb.scala:93)
[error]         at com.joakibj.tswrdb.TswRdb$$anonfun$15.apply(TswRdb.scala:92)
[error]         at scala.Option.map(Option.scala:145)
[error]         at com.joakibj.tswrdb.TswRdb$delayedInit$body.apply(TswRdb.scala
:91)
[error]         at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction
0.scala:12)
[error]         at scala.App$$anonfun$main$1.apply(App.scala:71)
[error]         at scala.App$$anonfun$main$1.apply(App.scala:71)
[error]         at scala.collection.immutable.List.foreach(List.scala:318)
[error]         at scala.collection.generic.TraversableForwarder$class.foreach(T
raversableForwarder.scala:32)
[error]         at scala.App$class.main(App.scala:71)
[error]         at com.joakibj.tswrdb.TswRdb$.main(TswRdb.scala:27)
[error]         at com.joakibj.tswrdb.TswRdb.main(TswRdb.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Sourc
e)
[error]         at java.lang.reflect.Method.invoke(Unknown Source)
[error]         at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(Sc
alaClassLoader.scala:71)
[error]         at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaCl
assLoader.scala:31)
[error]         at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContex
t(ScalaClassLoader.scala:139)
[error]         at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoa
der.scala:71)
[error]         at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(Scal
aClassLoader.scala:139)
[error]         at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)

[error]         at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
[error]         at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.s
cala:35)
[error]         at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:
45)
[error]         at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunn
er.scala:74)
[error]         at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.s
cala:96)
[error]         at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.sca
la:105)
[error]         at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scal
a)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last tswrdb-cmdui/compile:run for the full o
utput.
[error](tswrdb-cmdui/compile:run) Nonzero exit code returned from runner: 1
[error] Total time: 8 s, completed 7 nov. 2013 08:23:12

**Comment by joakibj** [comment]
Hi, thanks for the report :)

Actually "Icons - PNG" is a bit misleading, for some reason they are _Age of Conan_ icons. The TSW ones can be found in 1000624, but they are all flash

Anyways, I am a bit stumped as to this error since I am unable to reproduce it. If you have the latest source there is very few cases where this should be possible, especially since you can export other rdbtypes

Did tswrdb create the `exported/1010008 (Icons - PNG)` folder?

**Comment by Voyv** [comment]
Yes it created the folder.

Just did a : run export rdbtype 1000624 --tsw """C:\The Secret World - Test"""
It worked fine and extracted all .swf.

Only rdbtype 1010008 seems to cause errors.

EDIT : on win7 x64 using java 1.7.0_45, nothing special elsewhere.

**Comment by joakibj** [comment]
I see you have two TSW installations used there, `C:\The Secret World` and `C:\The Secret World - Test`. Does running the command for both directories produce the same errors for you?

Also, is it the latest updated TSW Live / TestLive?

**Comment by Voyv** [comment]
Yup, that's why i tried both (live & testlive client).

Edit: I figured my answer was not clear. Yes it produce the same error on both TSW installations and yes Live and TestLive client are both updated

**Comment by joakibj** [comment]
There might be a slight possibility that Funcom removed this rdbtype from the RDB databases, thus invalidating some entries in the index. Players with RDB databases that are new (e.g. fresh download) notice nothing, but players with old RDB databases have a lot of trash in them.

It is just a theory, otherwise I have no clue for this, sorry.
