### ISSUE TITLE
Specific RdbTypes Info

### ISSUE THREAD

**Issue by canuckkat** [joakibj/tswrdb#4]
This node.js TSW RDB Extractor project (http://aerobushentertainment.com/) has everything indexed in the attached file.

Rename the attached file extension to js to open it.

![rdbtypes_full](https://f.cloud.github.com/assets/996527/1936234/c3720ec4-7f06-11e3-9b47-1439aca979d4.jpg)

**Comment by joakibj** [comment]
The RdbTypes in tswrdb is based on the source you supplied there, with several additions and some removals.
